### ISSUE TITLE
Question about grouping

### ISSUE THREAD

**Issue by PythonNut** [EphramPerdition/helm-fuzzier#3]
Hey, just took this for a test drive, and seems to be working. Yay!

I'm trying to wrap my head around the code, and I can't figure out the significance of grouping the characters. (`helm-fuzzier--mapconcat-initials-pattern`)

There's a good chance I'm just being dumb.

**Comment by EphramPerdition** [comment]
What exactly do you mean by grouping? or is what the function does simply unclear?

**Comment by PythonNut** [comment]
I suppose I'm asking:

How does "exploding" all of the possible groupings (which, I suppose, is algorithmically equivalent to keeping the characters fixed, and moving the various numbers of separators around) differ from matching against, say `abc` ⇒ `a[^- /]*b[^- /]*c`.

I ask because your regex appears more restrictive. (A given run of letters must start a word?) However, I can still get `macs-isp-ode` to match `emacs-lisp-mode`, so it doesn't seem like the regex is affecting the quality of matches.

EDIT: Never mind, I see that the matches are additive, so the assumption that runs start at the beginning of words is done for optimization's sake.

**Comment by EphramPerdition** [comment]
> differ from matching against, say abc ⇒ a[^- /]_b[^- /]_c.

The regex is indeed more restrictive and that is exactly what it's there for. The goal is locate high-quality "Preferred Matches" first, in order to make sure they make it into the list `flx` gets to see. After that phase, Helm runs as usual and fills the matches quota with whatever (weak) fuzzy matches it finds. 

Each matching phase satisfies different use cases and any one without the other falls apart in some cases.

Note Helm already works well for a very long query such as `macs-isp-ode` because the number of fuzzy matches is well below LIMIT and `flx` thus gets to see **everything** that matches in candidates.

On the other hand, a short query like `elm` won't bring up anything except noise without `helm-fuzzier` because Helm will just take the first `LIMIT` (low-quality) matches it finds and then stop looking. `flx` can't boost results it doesn't see, so the user will usually not get what they were looking for.

This is explained at length in the `;;; Commentary:` and also the README as of a few hours ago.

**Comment by PythonNut** [comment]
Yup, thanks for the explanation here. I pulled repo yesterday and was reading an out-of-date README. :/

Looking forward to seeing this on MELPA!
